import type { FoodItem } from "@/types/food"

export const mockFoodItems: FoodItem[] = [
  {
    id: "mi1", // Updated to match new ID format
    name: "Classic Burger",
    description: "Beef patty with lettuce, tomato, and special sauce",
    price: 8.99,
    image: "/placeholder.svg?height=150&width=150",
    restaurant: "Burger Haven",
    restaurantId: "clz1", // Updated to match new restaurant ID format
    category: "Burgers", // Ensure consistency with the new category
    rating: 4.7,
    preparationTime: 15,
    calories: 850,
    ingredients: ["Beef patty", "Lettuce", "Tomato", "Special sauce"],
    allergens: ["Gluten", "Dairy", "Egg"],
  },
  {
    id: "mi2",
    name: "Cheeseburger",
    description: "Classic burger with American cheese",
    price: 9.99,
    image: "/placeholder.svg?height=150&width=150",
    restaurant: "Burger Haven",
    restaurantId: "clz1",
    category: "Burgers",
    rating: 4.6,
    preparationTime: 12,
    calories: 720,
    ingredients: ["Beef patty", "American cheese", "Lettuce", "Tomato", "Special sauce"],
    allergens: ["Gluten", "Dairy", "Egg"],
  },
  {
    id: "mi3",
    name: "French Fries",
    description: "Crispy golden fries",
    price: 3.99,
    image: "/placeholder.svg?height=150&width=150",
    restaurant: "Burger Haven",
    restaurantId: "clz1",
    category: "Sides",
    rating: 4.3,
    preparationTime: 8,
    calories: 320,
    ingredients: ["Potatoes", "Salt", "Oil"],
    allergens: ["None"],
  },
  {
    id: "mi4",
    name: "Margherita Pizza",
    description: "Tomato sauce, mozzarella, and basil",
    price: 12.99,
    image: "/placeholder.svg?height=150&width=150",
    restaurant: "Pizza Palace",
    restaurantId: "clz2", // Updated to match restaurant ID
    category: "Pizzas",
    rating: 4.8,
    preparationTime: 20,
    calories: 780,
    ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Basil"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "mi5",
    name: "Pepperoni Pizza",
    description: "Tomato sauce, mozzarella, and pepperoni",
    price: 14.99,
    image: "/placeholder.svg?height=150&width=150",
    restaurant: "Pizza Palace",
    restaurantId: "clz2",
    category: "Pizzas",
    rating: 4.7,
    preparationTime: 22,
    calories: 850,
    ingredients: ["Pizza dough", "Tomato sauce", "Mozzarella", "Pepperoni"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "mi6",
    name: "Garlic Bread",
    description: "Toasted bread with garlic butter",
    price: 4.99,
    image: "/placeholder.svg?height=150&width=150",
    restaurant: "Pizza Palace",
    restaurantId: "clz2",
    category: "Sides",
    rating: 4.4,
    preparationTime: 5,
    calories: 300,
    ingredients: ["Bread", "Garlic", "Butter"],
    allergens: ["Gluten", "Dairy"],
  },
]

export const foodCategories = ["Burgers", "Pizzas", "Sides"] // Updated for consistency
