import type { FoodItem } from "@/types/food"

export const mockFoodItems: FoodItem[] = [
  {
    id: "1",
    name: "Classic Cheeseburger",
    description:
      "Juicy beef patty with melted cheddar cheese, lettuce, tomato, and special sauce on a toasted brioche bun.",
    price: 12.99,
    image: "/placeholder.svg?height=300&width=300",
    restaurant: "Burger Haven",
    restaurantId: "r1",
    category: "Burgers",
    rating: 4.7,
    preparationTime: 15,
    calories: 850,
    ingredients: ["Beef patty", "Cheddar cheese", "Lettuce", "Tomato", "Onion", "Special sauce", "Brioche bun"],
    allergens: ["Gluten", "Dairy", "Egg"],
  },
  {
    id: "2",
    name: "Margherita Pizza",
    description:
      "Traditional Italian pizza with fresh mozzarella, tomatoes, basil, and extra virgin olive oil on a thin crust.",
    price: 14.99,
    image: "/placeholder.svg?height=300&width=300",
    restaurant: "Pizza Palace",
    restaurantId: "r2",
    category: "Pizza",
    rating: 4.5,
    preparationTime: 20,
    isVegetarian: true,
    calories: 780,
    ingredients: ["Pizza dough", "San Marzano tomatoes", "Fresh mozzarella", "Fresh basil", "Extra virgin olive oil"],
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "3",
    name: "Vegetable Pad Thai",
    description:
      "Stir-fried rice noodles with tofu, bean sprouts, green onions, and crushed peanuts in a sweet and savory sauce.",
    price: 13.99,
    image: "/placeholder.svg?height=300&width=300",
    restaurant: "Thai Delight",
    restaurantId: "r3",
    category: "Asian",
    rating: 4.3,
    preparationTime: 18,
    isVegetarian: true,
    isVegan: true,
    calories: 650,
    ingredients: ["Rice noodles", "Tofu", "Bean sprouts", "Green onions", "Crushed peanuts", "Pad Thai sauce"],
    allergens: ["Peanuts", "Soy"],
  },
  {
    id: "4",
    name: "Chicken Caesar Salad",
    description: "Crisp romaine lettuce with grilled chicken, parmesan cheese, croutons, and creamy Caesar dressing.",
    price: 11.99,
    image: "/placeholder.svg?height=300&width=300",
    restaurant: "Fresh Greens",
    restaurantId: "r4",
    category: "Salads",
    rating: 4.2,
    preparationTime: 10,
    calories: 450,
    ingredients: ["Romaine lettuce", "Grilled chicken breast", "Parmesan cheese", "Croutons", "Caesar dressing"],
    allergens: ["Gluten", "Dairy", "Egg"],
  },
  {
    id: "5",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with a molten chocolate center, served with vanilla ice cream.",
    price: 8.99,
    image: "/placeholder.svg?height=300&width=300",
    restaurant: "Sweet Treats",
    restaurantId: "r5",
    category: "Desserts",
    rating: 4.8,
    preparationTime: 15,
    isVegetarian: true,
    calories: 550,
    ingredients: ["Chocolate", "Flour", "Sugar", "Eggs", "Butter", "Vanilla ice cream"],
    allergens: ["Gluten", "Dairy", "Egg"],
  },
  {
    id: "6",
    name: "Veggie Wrap",
    description: "Spinach tortilla filled with hummus, avocado, mixed greens, cucumber, and bell peppers.",
    price: 9.99,
    image: "/placeholder.svg?height=300&width=300",
    restaurant: "Fresh Greens",
    restaurantId: "r4",
    category: "Wraps",
    rating: 4.1,
    preparationTime: 8,
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    calories: 380,
    ingredients: ["Spinach tortilla", "Hummus", "Avocado", "Mixed greens", "Cucumber", "Bell peppers"],
    allergens: ["Sesame"],
  },
  {
    id: "7",
    name: "Spicy Tuna Roll",
    description: "Fresh tuna, spicy mayo, cucumber, and avocado wrapped in seaweed and rice.",
    price: 15.99,
    image: "/placeholder.svg?height=300&width=300",
    restaurant: "Sushi Spot",
    restaurantId: "r6",
    category: "Sushi",
    rating: 4.6,
    preparationTime: 12,
    isGlutenFree: true,
    calories: 320,
    ingredients: ["Tuna", "Rice", "Nori", "Spicy mayo", "Cucumber", "Avocado"],
    allergens: ["Fish", "Egg", "Soy"],
  },
  {
    id: "8",
    name: "BBQ Pulled Pork Sandwich",
    description: "Slow-cooked pulled pork in tangy BBQ sauce, topped with coleslaw on a brioche bun.",
    price: 13.49,
    image: "/placeholder.svg?height=300&width=300",
    restaurant: "Smokey's BBQ",
    restaurantId: "r7",
    category: "Sandwiches",
    rating: 4.4,
    preparationTime: 10,
    calories: 720,
    ingredients: ["Pulled pork", "BBQ sauce", "Coleslaw", "Brioche bun"],
    allergens: ["Gluten", "Egg"],
  },
]

// Update these specific items to ensure they match our restaurant IDs
mockFoodItems[0].restaurantId = "r1" // Burger Haven
mockFoodItems[1].restaurantId = "r2" // Pizza Palace
mockFoodItems[2].restaurantId = "r3" // Thai Delight
mockFoodItems[3].restaurantId = "r4" // Fresh Greens
mockFoodItems[4].restaurantId = "r5" // Sweet Treats
mockFoodItems[5].restaurantId = "r4" // Fresh Greens
mockFoodItems[6].restaurantId = "r6" // Sushi Spot
mockFoodItems[7].restaurantId = "r7" // Smokey's BBQ

export const foodCategories = ["Burgers", "Pizza", "Asian", "Salads", "Desserts", "Wraps", "Sushi", "Sandwiches"]
