import type { Restaurant, MenuItem } from "./types"

export async function getRestaurant(id: string): Promise<Restaurant | null> {
  // In a real app, this would fetch from an API
  // For demo purposes, we're using mock data
  const restaurants: Restaurant[] = [
    {
      id: "1",
      name: "Burger Palace",
      image: "/placeholder.svg?height=400&width=800",
      cuisine: "American",
      rating: 4.5,
      deliveryTime: "20-30 min",
      deliveryFee: 2.99,
      featured: true,
    },
    {
      id: "2",
      name: "Pizza Heaven",
      image: "/placeholder.svg?height=400&width=800",
      cuisine: "Italian",
      rating: 4.7,
      deliveryTime: "25-35 min",
      deliveryFee: 3.99,
      featured: true,
    },
    {
      id: "3",
      name: "Sushi Express",
      image: "/placeholder.svg?height=400&width=800",
      cuisine: "Japanese",
      rating: 4.8,
      deliveryTime: "30-40 min",
      deliveryFee: 4.99,
      featured: true,
    },
    {
      id: "4",
      name: "Taco Fiesta",
      image: "/placeholder.svg?height=400&width=800",
      cuisine: "Mexican",
      rating: 4.3,
      deliveryTime: "15-25 min",
      deliveryFee: 2.49,
      featured: false,
    },
    {
      id: "5",
      name: "Curry House",
      image: "/placeholder.svg?height=400&width=800",
      cuisine: "Indian",
      rating: 4.6,
      deliveryTime: "25-40 min",
      deliveryFee: 3.49,
      featured: false,
    },
  ]

  const restaurant = restaurants.find((r) => r.id === id)
  return restaurant || null
}

export async function getMenuItems(restaurantId: string): Promise<MenuItem[]> {
  // In a real app, this would fetch from an API
  // For demo purposes, we're using mock data
  const menuItems: Record<string, MenuItem[]> = {
    "1": [
      {
        id: "101",
        restaurantId: "1",
        name: "Classic Cheeseburger",
        description: "Beef patty with cheese, lettuce, tomato, and special sauce",
        price: 8.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Burgers",
      },
      {
        id: "102",
        restaurantId: "1",
        name: "Bacon Deluxe Burger",
        description: "Beef patty with bacon, cheese, onion rings, and BBQ sauce",
        price: 10.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Burgers",
      },
      {
        id: "103",
        restaurantId: "1",
        name: "Chicken Sandwich",
        description: "Grilled chicken breast with lettuce, tomato, and mayo",
        price: 9.49,
        image: "/placeholder.svg?height=200&width=200",
        category: "Sandwiches",
      },
      {
        id: "104",
        restaurantId: "1",
        name: "French Fries",
        description: "Crispy golden fries with sea salt",
        price: 3.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Sides",
      },
    ],
    "2": [
      {
        id: "201",
        restaurantId: "2",
        name: "Margherita Pizza",
        description: "Tomato sauce, mozzarella, and basil",
        price: 12.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Pizzas",
      },
      {
        id: "202",
        restaurantId: "2",
        name: "Pepperoni Pizza",
        description: "Tomato sauce, mozzarella, and pepperoni",
        price: 14.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Pizzas",
      },
      {
        id: "203",
        restaurantId: "2",
        name: "Vegetarian Pizza",
        description: "Tomato sauce, mozzarella, bell peppers, mushrooms, and olives",
        price: 13.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Pizzas",
      },
      {
        id: "204",
        restaurantId: "2",
        name: "Garlic Bread",
        description: "Toasted bread with garlic butter and herbs",
        price: 4.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Sides",
      },
    ],
    "3": [
      {
        id: "301",
        restaurantId: "3",
        name: "California Roll",
        description: "Crab, avocado, and cucumber",
        price: 7.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Rolls",
      },
      {
        id: "302",
        restaurantId: "3",
        name: "Spicy Tuna Roll",
        description: "Spicy tuna and cucumber",
        price: 8.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Rolls",
      },
      {
        id: "303",
        restaurantId: "3",
        name: "Salmon Nigiri",
        description: "Fresh salmon over rice",
        price: 6.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Nigiri",
      },
      {
        id: "304",
        restaurantId: "3",
        name: "Miso Soup",
        description: "Traditional Japanese soup with tofu and seaweed",
        price: 3.49,
        image: "/placeholder.svg?height=200&width=200",
        category: "Sides",
      },
    ],
    "4": [
      {
        id: "401",
        restaurantId: "4",
        name: "Beef Taco",
        description: "Seasoned beef, lettuce, cheese, and salsa in a corn tortilla",
        price: 3.49,
        image: "/placeholder.svg?height=200&width=200",
        category: "Tacos",
      },
      {
        id: "402",
        restaurantId: "4",
        name: "Chicken Quesadilla",
        description: "Grilled chicken and cheese in a flour tortilla",
        price: 8.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Quesadillas",
      },
      {
        id: "403",
        restaurantId: "4",
        name: "Beef Burrito",
        description: "Seasoned beef, rice, beans, cheese, and salsa in a flour tortilla",
        price: 9.49,
        image: "/placeholder.svg?height=200&width=200",
        category: "Burritos",
      },
      {
        id: "404",
        restaurantId: "4",
        name: "Chips and Guacamole",
        description: "Crispy tortilla chips with fresh guacamole",
        price: 5.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Sides",
      },
    ],
    "5": [
      {
        id: "501",
        restaurantId: "5",
        name: "Chicken Tikka Masala",
        description: "Grilled chicken in a creamy tomato sauce",
        price: 14.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Curries",
      },
      {
        id: "502",
        restaurantId: "5",
        name: "Vegetable Biryani",
        description: "Basmati rice with mixed vegetables and spices",
        price: 12.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Rice Dishes",
      },
      {
        id: "503",
        restaurantId: "5",
        name: "Garlic Naan",
        description: "Flatbread with garlic and butter",
        price: 3.49,
        image: "/placeholder.svg?height=200&width=200",
        category: "Breads",
      },
      {
        id: "504",
        restaurantId: "5",
        name: "Samosas",
        description: "Fried pastry with spiced potatoes and peas",
        price: 5.99,
        image: "/placeholder.svg?height=200&width=200",
        category: "Appetizers",
      },
    ],
  }

  return menuItems[restaurantId] || []
}
